"""add_verification_history_and_fields

Revision ID: 47db55240115
Revises: af015547dba2
Create Date: 2026-06-15 16:39:55.179112
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47db55240115'
down_revision: Union[str, None] = 'af015547dba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('fields_requested', sa.JSON(), nullable=True),
    sa.Column('fields_updated', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['verification_documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.add_column('verification_documents', sa.Column('fields_to_edit', sa.JSON(), nullable=True))
    op.add_column('verification_documents', sa.Column('fields_updated', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_documents', 'fields_updated')
    op.drop_column('verification_documents', 'fields_to_edit')
    op.drop_table('verification_history')
    # ### end Alembic commands ###
