"""add nationality and photo requirements to student

Revision ID: af015547dba2
Revises: a530df413cb5
Create Date: 2026-06-15 15:20:40.701526
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af015547dba2'
down_revision: Union[str, None] = 'a530df413cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nationality_id', sa.String(length=14), nullable=False))
    op.add_column('students', sa.Column('faculty', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('nationality_id_photo_front', sa.String(length=255), nullable=False))
    op.add_column('students', sa.Column('nationality_id_photo_back', sa.String(length=255), nullable=False))
    op.alter_column('students', 'profile_picture_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'students', ['nationality_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'profile_picture_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('students', 'nationality_id_photo_back')
    op.drop_column('students', 'nationality_id_photo_front')
    op.drop_column('students', 'faculty')
    op.drop_column('students', 'nationality_id')
    # ### end Alembic commands ###
