"""Add firebase sync models

Revision ID: e6ad8b5c7df8
Revises: 20260601_01
Create Date: 2026-06-13 20:36:37.680378
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ad8b5c7df8'
down_revision: Union[str, None] = '20260601_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firebase_sync_cursors',
    sa.Column('cursor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_event_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cursor_id'),
    sa.UniqueConstraint('collection_name')
    )
    op.create_table('firebase_sync_failures',
    sa.Column('failure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('failure_id'),
    sa.UniqueConstraint('event_id')
    )
    op.add_column('attendance_records', sa.Column('firebase_event_id', sa.String(length=36), nullable=True))
    op.add_column('attendance_records', sa.Column('biometric_verified', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'attendance_records', ['firebase_event_id'])
    op.add_column('students', sa.Column('biometric_unlock_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('students', sa.Column('trusted_device_id', sa.String(length=120), nullable=True))
    op.add_column('students', sa.Column('trusted_device_registered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'trusted_device_registered_at')
    op.drop_column('students', 'trusted_device_id')
    op.drop_column('students', 'biometric_unlock_enabled')
    op.drop_constraint(None, 'attendance_records', type_='unique')
    op.drop_column('attendance_records', 'biometric_verified')
    op.drop_column('attendance_records', 'firebase_event_id')
    op.drop_table('firebase_sync_failures')
    op.drop_table('firebase_sync_cursors')
    # ### end Alembic commands ###
